openapi: 3.0.0
info:
  version: '0.1'
  titel: 'API Sentinelle'
servers:
  -
    url: 'http://api.sentinelle.com/v1'
    description: 'Api de Sentinelle'
paths:
  /register:
    get:
      operationId: 'App\Controller\SecurityController::register'
      responses:
        '200':
          description: 'Jeton de securité'
          content:
            application/json:
              schema:
                type: string
